/**
 * This code was generated by Builder.io
 */
import React from "react";
import { Card } from "react-bootstrap";
import { useDrag } from "react-dnd";

export interface ICandidateProps {
  candidateId: string;
  applicationId: string;
  fullName: string;
  currentInterviewStep: string;
  averageScore: number;
}

const Candidate: React.FC<ICandidateProps> = ({
  candidateId,
  fullName,
  averageScore,
}) => {
  const [{ isDragging }, drag] = useDrag(() => ({
    type: "CANDIDATE",
    item: { candidateId },
    collect: (monitor) => ({
      isDragging: !!monitor.isDragging(),
    }),
  }));

  return (
    <Card ref={drag} className="mb-3" style={{ opacity: isDragging ? 0.5 : 1 }}>
      <Card.Body>
        <h3 className="h5 mb-3">{fullName}</h3>
        <div className="d-flex">
          {[...Array(5)].map((_, index) => (
            <div
              key={index}
              className={`rounded-circle mr-1 ${
                index < averageScore ? "bg-success" : "bg-light"
              }`}
              style={{ width: "20px", height: "20px" }}
              aria-hidden="true"
            />
          ))}
          <span className="sr-only">Rating: {averageScore} out of 5</span>
        </div>
      </Card.Body>
    </Card>
  );
};

export default Candidate;
